// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var ADT$Reason = require("./ADT.bs.js");

Curry._2(Printf.printf(/* Format */[
          /* String */Block.__(2, [
              /* No_padding */0,
              /* String_literal */Block.__(11, [
                  " = ",
                  /* Int */Block.__(4, [
                      /* Int_d */0,
                      /* No_padding */0,
                      /* No_precision */0,
                      /* Char_literal */Block.__(12, [
                          /* "\n" */10,
                          /* End_of_format */0
                        ])
                    ])
                ])
            ]),
          "%s = %d\n"
        ]), ADT$Reason.s1[/* view */0], ADT$Reason.v1[/* eval */0]);

Curry._2(Printf.printf(/* Format */[
          /* String */Block.__(2, [
              /* No_padding */0,
              /* String_literal */Block.__(11, [
                  " = ",
                  /* Int */Block.__(4, [
                      /* Int_d */0,
                      /* No_padding */0,
                      /* No_precision */0,
                      /* Char_literal */Block.__(12, [
                          /* "\n" */10,
                          /* End_of_format */0
                        ])
                    ])
                ])
            ]),
          "%s = %d\n"
        ]), ADT$Reason.s2[/* view */0], ADT$Reason.v2[/* eval */0]);

/*  Not a pure module */
